### ISSUE TITLE
Slicer Kernel cannot start

### ISSUE THREAD

**Issue by bveeni** [Slicer/SlicerJupyter#72] opened 2022-05-05 03:38 UTC
Hi everyone, 

I am facing the issue of "unable to start kernel for slicer" , giving logs as
```
Switch to module:  "Welcome"
Loading Slicer RC file [/home/sliceruser/.slicerrc.py]
Jupyter connection file: [/home/sliceruser/.local/share/jupyter/runtime/kernel-2c7279ff-433a-43c2-88d2-f15696ba54fb.json]
error: [/home/sliceruser/Slicer/bin/SlicerApp-real] exit abnormally - Report the problem.
```

I am running docker image for 3D slicer 
docker run -p 8888:8888 -p49053:49053 -v "$PWD":/home/sliceruser/work --rm -ti lassoan/slicer-notebook:2021-10-15-b3077c2
It works fine on my local machine (windows) and I am able to use 3D slicer via Jupiter notebook.
However, its not working on my remote VM (Ubuntu 18.04). Whenever, I try to open Slicer in notebook, it prompts  message "kernel appear to die and restart automatically" but never succeed to start.
Any guidance would be great.
Here is image attached of logs
![image](https://user-images.githubusercontent.com/47835599/166860967-85343d51-e17f-4031-a193-468fecc047e6.png)

Thanks

**Comment by lassoan** [comment] 2022-05-05 04:26
Could you try with the latest image - `lassoan/slicer-notebook:latest`?

**Comment by bveeni** [comment] 2022-05-05 04:44
> Could you try with the latest image - `lassoan/slicer-notebook:latest`?

Hi, 
With latest image also, it didn't worked.
Also, is there any chance of conflict on network, since I am connected to organization VPN, since I am working on remote VMS for this case.
Along with above mentioned logs, after few times of restarting, this error message pops up as shown in image.
![image](https://user-images.githubusercontent.com/47835599/166864741-0e5e8f8d-b506-4c64-bbfd-01010f6f2993.png)
Thanks

**Comment by lassoan** [comment] 2022-05-05 04:50
I don't know what can cause a docker image not run in a certain system. I would expect that docker takes care of creating a reproducible environment.

Are the ports accessible and the current directory (`$PWD`) writable?

**Comment by bveeni** [comment] 2022-05-05 05:20
> I don't know what can cause a docker image not run in a certain system. I would expect that docker takes care of creating a reproducible environment.
> 
> Are the ports accessible and the current directory (`$PWD`) writable?

Yes they are all good.

**Comment by lassoan** [comment] 2022-06-26 02:39
I'm closing this issue because we got stuck for a long time and it is not likely that we can make progress with it.

**Closed by lassoan** 2022-06-26 02:39 UTC
