### ISSUE TITLE
Kernel doesn't start

### ISSUE THREAD

**Issue by Abdolraouf-KIE** [Slicer/SlicerJupyter#56] opened 2021-02-18 02:05 UTC
After creating a notebook with Slicer 4.11, the kernel dies and keeps restarting without success. Below is the  log i get. During this process a new instance of 3DSlicer is opened and then closed immediately.
I tried deleting my settings folder ( .config/NA-MIC )  and reinstalling the extension as well as re-downloading 3DSlicer but same thing happens. I'm not an expert at programming so comprehensive help would be much appreciated. 

platform: Slicer-4.11.20200930-linux-amd64 r29402

```
[I 09:38:25.441 NotebookApp] Kernel started: 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee, name: slicer-4.11
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:38:40.443 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:38:55.472 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:39:10.495 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:39:25.520 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
[W 09:39:25.551 NotebookApp] Timeout waiting for kernel_info reply from 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[W 09:39:30.091 NotebookApp] Nudge: attempt 10 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[W 09:39:35.122 NotebookApp] Nudge: attempt 20 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[W 09:39:40.147 NotebookApp] Nudge: attempt 30 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[I 09:39:40.532 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee restarted
[W 09:39:45.174 NotebookApp] Nudge: attempt 40 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[W 09:39:50.203 NotebookApp] Nudge: attempt 50 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
Switch to module:  "Welcome"
[W 09:39:55.229 NotebookApp] Nudge: attempt 60 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:39:58.544 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee restarted
[W 09:40:00.255 NotebookApp] Nudge: attempt 70 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[W 09:40:05.283 NotebookApp] Nudge: attempt 80 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[W 09:40:10.314 NotebookApp] Nudge: attempt 90 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:40:13.572 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee restarted
[W 09:40:15.351 NotebookApp] Nudge: attempt 100 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[W 09:40:20.380 NotebookApp] Nudge: attempt 110 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[I 09:40:25.326 NotebookApp] Saving file at /Untitled Folder/Untitled5.ipynb
[W 09:40:25.406 NotebookApp] Nudge: attempt 120 on kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee
[E 09:40:25.569 NotebookApp] Uncaught exception GET /api/kernels/3acaca7f-c1d7-4b80-9791-3e4224e1e9ee/channels?session_id=90c231b255574bad9283ee221e2b03d4 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8891', method='GET', uri='/api/kernels/3acaca7f-c1d7-4b80-9791-3e4224e1e9ee/channels?session_id=90c231b255574bad9283ee221e2b03d4', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/tornado/websocket.py", line 956, in _accept_connection
        await open_result
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/asyncio/futures.py", line 327, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/asyncio/futures.py", line 243, in result
        raise self._exception
    tornado.util.TimeoutError: Timeout
Switch to module:  "Welcome"
[W 09:40:26.603 NotebookApp] Replacing stale connection: 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee:90c231b255574bad9283ee221e2b03d4
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:40:28.608 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee restarted
[E 09:40:28.609 NotebookApp] KernelRestarter: restart callback <bound method ZMQChannelsHandler.on_kernel_restarted of ZMQChannelsHandler(3acaca7f-c1d7-4b80-9791-3e4224e1e9ee)> failed
    Traceback (most recent call last):
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/jupyter_client/restarter.py", line 86, in _fire_callbacks
        callback()
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 601, in on_kernel_restarted
        self._send_status_message('restarting')
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 597, in _send_status_message
        self.write_message(json.dumps(msg, default=date_default))
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/tornado/websocket.py", line 337, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:40:46.636 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee restarted
[E 09:40:46.637 NotebookApp] KernelRestarter: restart callback <bound method ZMQChannelsHandler.on_kernel_restarted of ZMQChannelsHandler(3acaca7f-c1d7-4b80-9791-3e4224e1e9ee)> failed
    Traceback (most recent call last):
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/jupyter_client/restarter.py", line 86, in _fire_callbacks
        callback()
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 601, in on_kernel_restarted
        self._send_status_message('restarting')
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 597, in _send_status_message
        self.write_message(json.dumps(msg, default=date_default))
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/tornado/websocket.py", line 337, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:41:04.676 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee restarted
[E 09:41:04.677 NotebookApp] KernelRestarter: restart callback <bound method ZMQChannelsHandler.on_kernel_restarted of ZMQChannelsHandler(3acaca7f-c1d7-4b80-9791-3e4224e1e9ee)> failed
    Traceback (most recent call last):
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/jupyter_client/restarter.py", line 86, in _fire_callbacks
        callback()
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 601, in on_kernel_restarted
        self._send_status_message('restarting')
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 597, in _send_status_message
        self.write_message(json.dumps(msg, default=date_default))
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/tornado/websocket.py", line 337, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
Switch to module:  "Welcome"
Jupyter connection file: [/home/raouf/.local/share/jupyter/runtime/kernel-3acaca7f-c1d7-4b80-9791-3e4224e1e9ee.json]
error: [/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/bin/SlicerApp-real] exit abnormally - Report the problem.
[I 09:41:19.715 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 3acaca7f-c1d7-4b80-9791-3e4224e1e9ee restarted
[E 09:41:19.716 NotebookApp] KernelRestarter: restart callback <bound method ZMQChannelsHandler.on_kernel_restarted of ZMQChannelsHandler(3acaca7f-c1d7-4b80-9791-3e4224e1e9ee)> failed
    Traceback (most recent call last):
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/jupyter_client/restarter.py", line 86, in _fire_callbacks
        callback()
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 601, in on_kernel_restarted
        self._send_status_message('restarting')
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 597, in _send_status_message
        self.write_message(json.dumps(msg, default=date_default))
      File "/home/raouf/Documents/Tools/Slicer-4.11.20200930-linux-amd64/lib/Python/lib/python3.6/site-packages/tornado/websocket.py", line 337, in write_message
        raise WebSocketClosedError()
    tornado.websocket.WebSocketClosedError
Switch to module:  "Welcome"
```

**Comment by lassoan** [comment] 2022-06-26 02:51
I'm closing old tickets now. Hopefully the problem is resolved in Slicer-5.x.

**Closed by lassoan** 2022-06-26 02:51 UTC
